package com.freelancego.enums;

public enum NotificationType {
    // Milestone lifecycle
    MILESTONE_CREATED,
    MILESTONE_SUBMITTED,
    MILESTONE_APPROVED,
    MILESTONE_REJECTED,
    MILESTONE_REVISION_REQUESTED,
    MILESTONE_MODIFIED,
    MILESTONE_DELETED,
    MILESTONE_COMPLETED,

    // Payments
    MILESTONE_PAYMENT_INITIATED,
    MILESTONE_PAYMENT_COMPLETED,
    MILESTONE_PAYMENT_FAILED,
    MILESTONE_REFUNDED,

    // Job & bids
    JOB_CREATED,
    JOB_UPDATED,
    JOB_DELETED,
    BID_RECEIVED,
    BID_ACCEPTED,
    BID_REJECTED,
    JOB_BID_WITHDRAWN,

    // Communication
    MESSAGE_RECEIVED,

    // Disputes
    MILESTONE_DISPUTE_CREATED,
    MILESTONE_DISPUTE_RESOLVED
}