#spring.application.name=FreelanceGoBackend
#server.port=8080
#
## ===============================
## DATABASE
## ===============================
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.hikari.auto-commit=false
#
## ===============================
## GOOGLE OAUTH
## ===============================
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#
## ===============================
## ABLY
## ===============================
#ably.app.id=${ABLY_APP_ID}
#ably.key=${ABLY_KEY}
#ably.secret=${ABLY_SECRET}
#ably.cluster=${ABLY_CLUSTER}
#ably.api.key=${ABLY_API_KEY}
#
## ===============================
## SUPABASE
## ===============================
#supabase.url=${SUPABASE_URL}
#supabase.key=${SUPABASE_KEY}
#supabase.public-bucket=${SUPABASE_BUCKET}
#
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=10MB
#spring.jpa.properties.hibernate.jdbc.batch_size=10


spring.application.name=FreelanceGoBackend
spring.security.oauth2.client.registration.google.client-id=330369840125-nid24d1qhebdf9h73f7oe4stfukhmetu.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
server.port=8080

# PostgresSQL  Database Configuration (Local)
spring.datasource.url=jdbc:postgresql://localhost:5432/FreelanceGo
spring.datasource.username=postgres
spring.datasource.password=zxc007

# Deployed Database on Render
#spring.datasource.url=jdbc:postgresql://CYm9N1Ar9PLhoL67jdSmmludIaLzBAz1@dpg-d5q78de3jp1c739adl00-a.oregon-postgres.render.com:5432/freelancego_db_5
#spring.datasource.username=freelancego_db_5_user
#spring.datasource.password=CYm9N1Ar9PLhoL67jdSmmludIaLzBAz1

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.jpa.properties.hibernate.jdbc.batch_size=10

# Ably credentials for chat
APP_ID=2034581
KEY=b0dddaee8d0f9b6e5184
SECRET=a8835ef845596e8f4f7a
CLUSTER=ap2
YOUR_ABLY_API_KEY=OtSgGA.cAWR0g:rv1IQX4OtdQJLwINZeD4_v4JB3WpW26PZMlzjQ2UVLQ

# Supabase credentials for file upload
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.public-bucket=${SUPABASE_BUCKET}

